on: [push, pull_request]
name: CI
jobs:
  build:
    name: "Build on Racket '${{ matrix.racket-version }}' (${{ matrix.racket-variant }})"
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental || false }}
    strategy:
      fail-fast: false
      matrix:
        racket-version: ["stable", "current"]
        racket-variant: ["BC", "CS"]
        include:
          - racket-version: current
            experimental: true
    steps:
      - uses: actions/checkout@v2
      - uses: Bogdanp/setup-racket@v1.7
        with:
          architecture: x64
          distribution: full
          variant: ${{ matrix.racket-variant }}
          version: ${{ matrix.racket-version }}
      - name: Installing composable-promises-blog and its dependencies
        run: raco pkg install --no-docs --auto --name composable-promises-blog
      - name: Compiling composable-promises-blog and building its docs
        run: raco setup --check-pkg-deps --unused-pkg-deps composable-promises-blog
      - name: Testing composable-promises-blog
        run: raco test -x -p composable-promises-blog
