# Generated by Django 2.0.3 on 2018-06-07 13:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import memoryApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('memoryApp', '0003_auto_20180607_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='importance',
            field=models.FloatField(default=5, help_text='Should be a number from 0 to 10 (inclusive), not necessarily an integer. 10 is extremely important.', validators=[memoryApp.models.validateImportance]),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, help_text="Should be the address or name of the place where the event occurred. Don't worry too much about formatting.", max_length=511),
        ),
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(db_index=True, default='placeholder', max_length=511),
        ),
        migrations.AddField(
            model_name='eventlink',
            name='event',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='memoryApp.Event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventtag',
            name='event',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='memoryApp.Event'),
            preserve_default=False,
        ),
    ]
