# Generated by Django 2.0.3 on 2018-06-07 13:41

from django.db import migrations, models
import memoryApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('memoryApp', '0005_auto_20180607_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='importance',
            field=models.FloatField(help_text='Should be a number from 0 to 10 (inclusive), not necessarily an integer. 10 is extremely important.', validators=[memoryApp.models.validateImportance]),
        ),
    ]
