# Generated by Django 2.0.3 on 2018-06-07 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memoryApp', '0006_auto_20180607_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlink',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memoryApp.Event'),
        ),
        migrations.AlterField(
            model_name='eventtag',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memoryApp.Event'),
        ),
    ]
