# Generated by Django 2.0.3 on 2018-03-23 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.FloatField()),
                ('type', models.CharField(choices=[('CA', 'cash'), ('DB', 'debit'), ('DW', 'deposit or withdrawl')], default='CA', max_length=2)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
