# Generated by Django 2.0.3 on 2018-03-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('CA', 'cash'), ('DB', 'debit'), ('DW', 'deposit or withdrawal')], default='CA', max_length=2),
        ),
    ]
